@BASE_URL = http://localhost:9999
@ACCESS_TOKEN = {{login.response.body.access_token}}
@locationId=c2a40b6a-64c6-4d5c-88c6-471ccdaa327b
@LOC2=14f66239-de40-4575-aea1-f7d7405b4695
@LOC3=421602e9-efda-4229-922f-f3e0b032b47a
@LOC4=8a703ffd-79b4-410d-ae14-a5991cf3f43e

### Login
# @name login
POST {{BASE_URL}}/api/auth/login
Content-Type: application/json

{
    "username": "superadmin",
    "password": "admin88"
}

### Create location
POST {{BASE_URL}}/api/locations
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

{
    "name": "Table 4",
    "displayName": "T4"
}

### Get location by Id
GET {{BASE_URL}}/api/locations/{{locationId}}