@BASE_URL = process.env.BASE_URL
@ACCESS_TOKEN = {{login.response.body.access_token}}
@RESET_TOKEN = {{reset.response.body.resetToken}}

### GET home
GET  {{BASE_URL}}

### REGISTER
POST {{BASE_URL}}/api/auth/register
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
    "username": "aek",
    "password": "pppppp",
    "phone": "45345",
    "email": "n@gmail.com",
    "firstname": "aek",
    "lastname": "bleach"
}

### Login
# to grab response from below request and save in login
# @name login
POST {{BASE_URL}}/api/auth/login
Content-Type: application/json

{
    "username": "superadmin",
    "password": "admin88"
}

### GET my info
GET {{BASE_URL}}/api/auth/me
Authorization: Bearer {{ACCESS_TOKEN}}

// TO BE IMPLEMENTED LATER 
### POST forgot password
# @name reset
POST {{BASE_URL}}/api/auth/forgot-password
Content-Type: application/json

{
    "email" : "4352345"
}

### PATCH reset password
PATCH {{BASE_URL}}/api/auth/reset-password/{{RESET_TOKEN}} 
Content-Type: application/json

{
    "password": "hehehehe"
}