@BASE_URL = {{baseUrl}}
@ACCESS_TOKEN = {{login.response.body.access_token}}
@locationId=c2a40b6a-64c6-4d5c-88c6-471ccdaa327b
@groupId=9a071ddb-5d94-4d2b-a8ad-1367360cea72
@LOC2=14f66239-de40-4575-aea1-f7d7405b4695

### Login
# @name login
POST {{BASE_URL}}/api/auth/login
Content-Type: application/json

{
    "username": "superadmin",
    "password": "admin88"
}

### Order Preview
POST {{BASE_URL}}/api/orders/preview
Content-Type: application/json

{
    "sessionIds": [167, 168]
}

# "endTime": "2026-04-01T11:42:36.075Z"

### Create order
POST {{BASE_URL}}/api/orders
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
    "sessionIds": [44, 45],
    "createdById": 2
}

### Get orders
GET {{BASE_URL}}/api/orders?status=PAID&id=32
Authorization: Bearer {{ACCESS_TOKEN}}

### Get order by id
GET {{BASE_URL}}/api/orders/45
Authorization: Bearer {{ACCESS_TOKEN}}

### Update order by id
PATCH {{BASE_URL}}/api/orders/1
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
    "status": "UNPAID",
    "updatedById": 2
}

### Delete order by id
DELETE {{BASE_URL}}/api/orders/2
Authorization: Bearer {{ACCESS_TOKEN}}