@BASE_URL = {{baseUrl}}
@ACCESS_TOKEN = {{login.response.body.access_token}}
@locationId=c2a40b6a-64c6-4d5c-88c6-471ccdaa327b
@groupId=9a071ddb-5d94-4d2b-a8ad-1367360cea72
@LOC2=14f66239-de40-4575-aea1-f7d7405b4695
@LOC3=421602e9-efda-4229-922f-f3e0b032b47a
@LOC5=1d9a4884-ce9d-435c-8dde-6a53dbf8614c
@RockyGROUP=092e9bc0-6cb7-4c94-9461-11797cbc3d0d
### Login
# @name login
POST {{BASE_URL}}/api/auth/login
Content-Type: application/json

{
    "username": "superadmin",
    "password": "admin88"
}

### Get filtered session
GET {{BASE_URL}}/api/sessions/filter?locationId={{LOC3}}&groupId={{RockyGROUP}}

### Get all sessions
# locationId={{locationId}}&groupId={{groupId}}
# GET {{BASE_URL}}/api/sessions
GET {{BASE_URL}}/api/sessions
Authorization: Bearer {{ACCESS_TOKEN}}

### Create session
POST {{BASE_URL}}/api/sessions
Content-Type: application/json

{
    "locationId": "c2a40b6a-64c6-4d5c-88c6-471ccdaa327b", 
    "groupId": null, 
    "names": ["Poom", "Peach"],
    "people": 2,
    "pricingId": 1
}

### Get session by Id
GET {{BASE_URL}}/api/sessions/151

### Update session by Id
PATCH {{BASE_URL}}/api/sessions/45
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
    "status": "ENDED", 
    "endTime": "2026-03-26T05:36:00.000Z",
    "name": "Apple",
    "updatedById": 23
}

    # "pricingId": 1
# patch later
# { locationId, groupId, pricingId }

### Delete session by Id
DELETE {{BASE_URL}}/api/sessions/1
Authorization: Bearer {{ACCESS_TOKEN}}

### Update session by Group
# TO DO: add start time patch later
PATCH {{BASE_URL}}/api/sessions/groups/3f585963-d751-410a-a8e1-5f861c4fd8d9
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
    "status": "ENDED"
}

### Update session by individual session ids
PATCH {{BASE_URL}}/api/sessions/end
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
    "status": "ENDED",
    "sessionIds": [1, 2, 3],
     "endTime": "2026-03-26T05:36:00.000Z"
}

# console.log(new Date("2026-03-24 18:15:00").toISOString());