@BASE_URL = {{baseUrl}}
@ACCESS_TOKEN = {{login.response.body.access_token}}

### Login
# @name login
POST {{BASE_URL}}/api/auth/login
Content-Type: application/json

{
    "username": "aek",
    "password": "pppppp"
}

### Get all users
GET {{BASE_URL}}/api/users/
Authorization: Bearer {{ACCESS_TOKEN}}

### Get user by id
GET {{BASE_URL}}/api/users/8
Authorization: Bearer {{ACCESS_TOKEN}}

### Update user by id
PATCH {{BASE_URL}}/api/users/23
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
        "username": "Aek", 
        "password": "555555", 
        "email": "aek@gmail.com", 
        "firstname": "Aekkalard", 
        "lastname": "Phouansy", 
        "phone": "59991111"
}

### Delete user by id
DELETE {{BASE_URL}}/api/users/3
Authorization: Bearer {{ACCESS_TOKEN}}
